// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/16/2025, 6:10:34 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/gimhangyeol/politican_community/politician_community_front/politician-map/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/plugins/**/*.{js,ts,mjs}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/composables/**/*.{js,ts,mjs}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/utils/**/*.{js,ts,mjs}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/gimhangyeol/politican_community/politician_community_front/politician-map/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;